Update Build and Release.yml

diff --git a/.github/workflows/Build and Release.yml b/.github/workflows/Build and Release.yml
--- a/.github/workflows/Build and Release.yml
+++ b/.github/workflows/Build and Release.yml
@@ -168,11 +168,12 @@ jobs:
         downloaded_file=$(ls -t | head -n1)
         mv "$downloaded_file" "Build Components/"
         orion="Build Components/$downloaded_file"
+        echo "orion path: $orion"
+
         
         #Check Hash
         if [[ "${SHA256}" != "noSHA" ]]; then
           echo "Expected SHA256 Hash: ${SHA256}"
-          echo "orion path: $orion"
           calculated_sha256=$(shasum -a 256 "$orion" | awk '{print $1}')
           echo "Calculated SHA256 Hash: $calculated_sha256"
           if [[ "${calculated_sha256}" == "${SHA256}" ]]; then
@@ -220,10 +221,10 @@ jobs:
         # Download the Packages file
         curl -sSL https://repo.dynastic.co/Packages -o Packages
     
-        # Use awk to find entries for dev.theos.orion14, Architecture: iphoneos-arm, find the highest version
+        # Use awk to find entries for com.spos, Architecture: iphoneos-arm, find the highest version
         # extract the version, filename, SHA256 Hash, and MD5 hash
         SPOSIFYVERSION=$(awk 'BEGIN { RS = ""; FS = "\n"; highest_version = "" } $1 ~ /^Package: com.spos$/ && $0 ~ /Architecture: iphoneos-arm([^6]|$)/ { for (i = 1; i <= NF; i++) { if ($i ~ /^Version: /) { split($i, a, " "); version = a[2]; if (highest_version == "" || version > highest_version) { highest_version = version } } } } END { if (highest_version != "") print highest_version }' Packages)
-        echo "Sposify Version Extracted: $ORIONVERSION"
+        echo "Sposify Version Extracted: $SPOSIFYVERSION"
         FILENAME=$(awk 'BEGIN{RS="";FS="\n";highest_version=""} $1~/^Package: com.spos$/ && $0~/Architecture: iphoneos-arm/{current_version="";current_filename="";for(i=1;i<=NF;i++){if($i~/^Version: /){split($i,a," ");version=a[2];if(current_version==""||version>current_version){current_version=version}}else if($i~/^Filename: /){split($i,a," ");current_filename=a[2]}}if(highest_version==""||current_version>highest_version){highest_version=current_version;highest_filename=current_filename}} END{if(highest_version!="")print highest_filename}' Packages)
         echo "Sposify FileName Extracted: $FILENAME"
         SHA256=$(awk 'BEGIN{RS="";FS="\n";highest_version="";sha256="noSHA"} $1~/^Package: com.spos$/ && $0~/Architecture: iphoneos-arm/{current_version="";sha256_found=0;for(i=1;i<=NF;i++){if($i~/^Version: /){split($i,a," ");version=a[2];if(current_version==""||version>current_version){current_version=version}}else if($i~/^SHA256: /){split($i,a," ");sha256=a[2];sha256_found=1}}if(highest_version==""||current_version>highest_version){highest_version=current_version;if(sha256_found==1){highest_sha256=sha256}else{highest_sha256="noSHA"}}}END{if(highest_version!="")print highest_sha256}' Packages)
@@ -237,11 +238,11 @@ jobs:
         downloaded_file=$(ls -t | head -n1)
         mv "$downloaded_file" "Build Components/"
         sposify="Build Components/$downloaded_file"
+        echo "Sposify path: $sposify"
         
         #Check Hash
         if [[ "${SHA256}" != "noSHA" ]]; then
           echo "Expected SHA256 Hash: ${SHA256}"
-          echo "Sposify path: $sposify"
           calculated_sha256=$(shasum -a 256 "$sposify" | awk '{print $1}')
           echo "Calculated SHA256 Hash: $calculated_sha256"
           if [[ "${calculated_sha256}" == "${SHA256}" ]]; then
@@ -285,21 +286,69 @@ jobs:
       if: ${{ env.VIRUSTOTALKEY }}
       run: echo "VTSPOSIFY=${{ steps.vt-sposify.outputs.analysis }}" >> $GITHUB_ENV
 
-    - name: Download SposifyFix .deb file from Level3tjg repo
+    - name: Download and process SposifyFix
       run: |
-        sposifyfix_url=$(curl -s https://level3tjg.me/repo/Packages | jq -r '.[] | select(.package=="com.level3tjg.sposifyfix").version')
-        sposifyfix_version=$(echo $sposifyfix_url | jq -r .version)
-        sposifyfix_download_url=$(echo $sposifyfix_url | jq -r .url)
-        curl -L "$sposifyfix_download_url" -o "Build Components/sposifyfix"
-        echo "sposifyfix=Build Components/sposifyfix" >> $GITHUB_ENV
-        echo "SPOSIFYFIXVERSION=$sposifyfix_version" >> $GITHUB_ENV
+        # Download the Packages file
+        curl -sSL https://level3tjg.me/repo/Packages -o Packages
+    
+        # Use awk to find entries for dev.theos.orion14, Architecture: iphoneos-arm, find the highest version
+        # extract the version, filename, SHA256 Hash, and MD5 hash
+        SPOSIFYFIXVERSION=$(awk 'BEGIN { RS = ""; FS = "\n"; highest_version = "" } $1 ~ /^Package: com.level3tjg.sposifyfix$/ && $0 ~ /Architecture: iphoneos-arm([^6]|$)/ { for (i = 1; i <= NF; i++) { if ($i ~ /^Version: /) { split($i, a, " "); version = a[2]; if (highest_version == "" || version > highest_version) { highest_version = version } } } } END { if (highest_version != "") print highest_version }' Packages)
+        echo "Sposify Version Extracted: $SPOSIFYFIXVERSION"
+        FILENAME=$(awk 'BEGIN{RS="";FS="\n";highest_version=""} $1~/^Package: com.level3tjg.sposifyfix$/ && $0~/Architecture: iphoneos-arm/{current_version="";current_filename="";for(i=1;i<=NF;i++){if($i~/^Version: /){split($i,a," ");version=a[2];if(current_version==""||version>current_version){current_version=version}}else if($i~/^Filename: /){split($i,a," ");current_filename=a[2]}}if(highest_version==""||current_version>highest_version){highest_version=current_version;highest_filename=current_filename}} END{if(highest_version!="")print highest_filename}' Packages)
+        echo "Sposify FileName Extracted: $FILENAME"
+        SHA256=$(awk 'BEGIN{RS="";FS="\n";highest_version="";sha256="noSHA"} $1~/^Package: com.level3tjg.sposifyfix$/ && $0~/Architecture: iphoneos-arm/{current_version="";sha256_found=0;for(i=1;i<=NF;i++){if($i~/^Version: /){split($i,a," ");version=a[2];if(current_version==""||version>current_version){current_version=version}}else if($i~/^SHA256: /){split($i,a," ");sha256=a[2];sha256_found=1}}if(highest_version==""||current_version>highest_version){highest_version=current_version;if(sha256_found==1){highest_sha256=sha256}else{highest_sha256="noSHA"}}}END{if(highest_version!="")print highest_sha256}' Packages)
+        echo "Sposify SHA256 Hash Extracted: $SHA256"
+        MD5=$(awk 'BEGIN{RS="";FS="\n";highest_version="";md5sum="noMD5"} $1~/^Package: ccom.level3tjg.sposifyfix$/ && $0~/Architecture: iphoneos-arm/{current_version="";for(i=1;i<=NF;i++){if($i~/^Version: /){split($i,a," ");version=a[2];if(current_version==""||version>current_version){current_version=version}}else if($i~/^MD5Sum: /){split($i,a," ");md5sum=a[2]}}if(highest_version==""||current_version>highest_version){highest_version=current_version;highest_md5sum=md5sum}} END{if(highest_version!="")print highest_md5sum}' Packages)
+        echo "Sposify MD5 Hash Extracted: $MD5"
+
+        echo "Downloading From: https://level3tjg.me/repo/Packages/$FILENAME"
+        # Download the file using curl
+        curl -LJO "https://level3tjg.me/repo/$FILENAME"
+        downloaded_file=$(ls -t | head -n1)
+        mv "$downloaded_file" "Build Components/"
+        sposifyfix="Build Components/$downloaded_file"
+        echo "SposifyFix path: $sposifyfix"
+        
+        #Check Hash
+        if [[ "${SHA256}" != "noSHA" ]]; then
+          echo "Expected SHA256 Hash: ${SHA256}"
+          calculated_sha256=$(shasum -a 256 "$sposifyfix" | awk '{print $1}')
+          echo "Calculated SHA256 Hash: $calculated_sha256"
+          if [[ "${calculated_sha256}" == "${SHA256}" ]]; then
+            echo "SHA256 matches. Continuing..."
+          else
+            echo "SHA256 does not match."
+            exit 1
+          fi
+        elif [[ "${MD5}" != "noMD5" ]]; then
+          echo "Expected MD5 Hash: ${MD5}"
+          calculated_md5=$(md5 -q "$sposifyfix" | awk '{print $1}')
+          echo "Calculated MD5 Hash: $calculated_md5"
+          if [[ "${calculated_md5}" == "${MD5}" ]]; then
+            echo "MD5 matches. Continuing..."
+          else
+            echo "MD5 does not match."
+            exit 1
+          fi
+        else
+          echo "Neither SHA256 nor MD5 is valid"
+          exit 1
+        fi
+
+        #CleanUp
+        rm -f Packages
+
+        #Set Env Varibles
+        echo "sposifyfix=Build Components/$downloaded_file" >> $GITHUB_ENV
+        echo "SPOSIFYFIXVERSION=$sposify_version" >> $GITHUB_ENV
     
     - name: Upload SposifyFix to VirusTotal
       if: ${{ env.VIRUSTOTALKEY }}
       uses: crazy-max/ghaction-virustotal@v4
       id: vt-sposifyfix
       with:
-        files: "Build Components/sposifyfix"
+        files: "${{ env.sposifyfix }}"
         vt_api_key: ${{ env.VIRUSTOTALKEY }}
         
     - name: Set VirusTotal Analysis URL for SposifyFix
@@ -333,25 +382,24 @@ jobs:
 
     - name: Duplicate and unzip Spotify.ipa
       run: |
-        cp "Build Components/Spotify.ipa" "Build Components/SpotifyAnylises.zip"
-        unzip "Build Components/SpotifyAnylises.zip" -d payload
+        cp "${{ env.spotifypath }}" "Build Components/SpotifyAnylises.zip"
+        unzip "Build Components/SpotifyAnylises.zip"
     
     - name: Extract info.plist from Spotify
       run: |
-        cp payload/Payload/Spotify.app/Info.plist "Build Components/Info.plist"
+        cp Payload/Spotify.app/Info.plist "Build Components/Info.plist"
         echo "VANILLASPOTIFYVERSION=$(defaults read "Build Components/Info.plist" CFBundleVersion)" >> $GITHUB_ENV
     
     - name: Modify Spotify with OpenSpotifySafariExtension.appex
       run: |
-        cp "Build Components/OpenSpotifySafariExtension.appex" payload/Payload/Spotify.app/PlugIns/
-        cd payload
-        zip -r ../Build\ Components/SpotifyEXT.zip ./*
-        cd ../Build\ Components
+        cp "Build Components/OpenSpotifySafariExtension.appex" Payload/Spotify.app/PlugIns/
+        zip -r SpotifyEXT.zip Payload
+        cd ""Build Components/"
         mv SpotifyEXT.zip SpotifyEXT.ipa
         echo "spotifyEXTpath=Build Components/SpotifyEXT.ipa" >> $GITHUB_ENV
-        rm -rf payload
-        rm SpotifyAnylises.zip
-        rm Info.plist
+        rm -rf Payload
+        rm -f SpotifyAnylises.zip
+        rm -f Info.plist
     
     - name: Set Change Version
       id: set-change-version
